SEED: 0
ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
  ITERATOR_OPTIONS:
    SHUFFLE: False
SIMULATOR:
  ACTION_SPACE_CONFIG: v1
  AGENT_0:
    SENSORS: [RGB_SENSOR, DEPTH_SENSOR]
    HEIGHT: 0.88
    RADIUS: 0.1
  FORWARD_STEP_SIZE: 0.25
  TURN_ANGLE: 30
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    ALLOW_SLIDING: True
  RGB_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    HFOV: 79
    POSITION: [0, 0.88, 0]
    TYPE: HabitatSimRGBSensor
  DEPTH_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    HFOV: 79
    MIN_DEPTH: 0.1
    MAX_DEPTH: 5.0
    POSITION: [0, 0.88, 0]
  TYPE:
    Sim-v1
TASK:
  TYPE: ObjectNav-v1
  SUCCESS_DISTANCE: 1.0
  SENSORS: [
    COMPASS_SENSOR,
    GPS_SENSOR,
    SENSOR_POSE_SENSOR,
    POSITION_SENSOR,
    HEADING_SENSOR
  ]
  GOAL_SENSOR_UUID: objectgoal
  POSSIBLE_ACTIONS: [STOP, MOVE_FORWARD, TURN_LEFT, TURN_RIGHT, LOOK_UP, LOOK_DOWN]
  MEASUREMENTS: [
    DISTANCE_TO_GOAL,
    SUCCESS,
    SPL,
    ORACLE_SUCCESS,
    PATH_LENGTH,
    STEPS_TAKEN,
    POSITION
  ]
  DISTANCE_TO_GOAL:
    DISTANCE_TO: VIEW_POINTS
  SUCCESS:
    SUCCESS_DISTANCE: 1.0
DATASET:
  TYPE: ObjectNav-v1
  SPLIT: val
  
  DATA_PATH: data/datasets/episodes/hm3d_ovon.json.gz
  SCENES_DIR: data/scene_datasets/hm3d